//改变当前的分类
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
// 把接口中得到的轮播数组放置到仓库中
export const  SET_HOME_SLIDERS = "SET_HOME_SLIDERS"

export const SET_HOME_LESSONS = "SET_HOME_LESSONS"

export const RESET_HOME_LESSONS = "RESET_HOME_LESSONS"

export const REFRESH_HOME_LESSONS = "REFRESH_HOME_LESSONS"

export const SET_HOME_LESSONS_LOADING = "SET_HOME_LESSONS_LOADING"

export const GET_DETAIL = "GET_DETAIL"

export const SET_USER = "SET_USER"